server:
  port: 9090

spring:
  security:
    user:
      name: admin
      password: admin
    oauth2:
      authorizationserver:
        client:
          oidc-test:
            registration:
              client-id: oidc-test
              client-secret: "{noop}Uq8odAqLX59MuZfNXRwgSRPA3w4qz5TW"
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
                - none
              authorization-grant-types:
                - authorization_code
                - client_credentials
                - refresh_token
              redirect-uris:
                - http://localhost:8080
                - http://localhost:8081
              post-logout-redirect-uris:
                - http://localhost:8080
                - http://localhost:8081
              scopes:
                - openid
                - profile
                - email
            require-authorization-consent: false
            