server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: admin
      password: admin
    oauth2:
      authorizationserver:
#        issuer: http://localhost:9000
        client:
          oidc-test:
            registration:
              client-id: oidc-test
              client-secret: "{noop}secret"
              client-authentication-methods:
#                - none
#                - client_secret_post
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - client_credentials
                - refresh_token
              redirect-uris:
#                - http://localhost:8080
                - http://localhost:8081
              post-logout-redirect-uris:
#                - http://localhost:8080
                - http://localhost:8081
              scopes:
                - openid
                - profile
                - email
            require-authorization-consent: false
#            require-proof-key: true
            